[package]
name = "pont-secure-net"
version = "0.1.0"
authors = ["Pont Labs <opensource@pontlabs.com>"]
repository = "https://github.com/aptos-labs/pont-core"
description = "Pont's Simple Network Substrate"
homepage = "https://pontlabs.com"
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
once_cell = "1.10.0"
serde = { version = "1.0.137", features = ["rc"], default-features = false }
thiserror = "1.0.31"

pont-logger = { path = "../../crates/pont-logger" }
pont-metrics-core = { path = "../../crates/pont-metrics-core" }
[dev-dependencies]
pont-config = { path = "../../config" }
