[package]
name = "pont-aggregator"
version = "0.1.0"
authors = ["Pont Labs <opensource@pontlabs.com>"]
description = "Aggregator sources for the Pont blockchain"
repository = "https://github.com/aptos-labs/pont-core"
homepage = "https://pontlabs.com"
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
anyhow = "1.0.57"
bcs = { git = "https://github.com/aptos-labs/bcs", rev = "2cde3e8446c460cb17b0c1d6bac7e27e964ac169" }
better_any = "0.1.1"
once_cell = "1.10.0"
smallvec = "1.8.0"

pont-crypto = { path = "../../crates/pont-crypto" }
pont-state-view = { path = "../../storage/state-view" }
pont-types = { path = "../../types" }
move-binary-format = { workspace = true }

move-core-types = { workspace = true }
move-table-extension = { workspace = true }

[dev-dependencies]
claims = "0.7"

[features]
default = []
