[package]
name = "hello_prover"
version = "0.0.0"

[dependencies]
PontFramework = { git = "https://github.com/aptos-labs/pont-core.git", subdir = "pont-move/framework/pont-framework/", rev = "main" }

[addresses]


