[package]
name = "network-discovery"
version = "0.1.0"
authors = ["Pont Labs <opensource@pontlabs.com>"]
description = "Pont Network Peer Discovery"
repository = "https://github.com/aptos-labs/pont-core"
homepage = "https://pontlabs.com"
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
anyhow = "1.0.57"
bcs = { git = "https://github.com/aptos-labs/bcs", rev = "2cde3e8446c460cb17b0c1d6bac7e27e964ac169" }
futures = "0.3.21"
once_cell = "1.10.0"
serde_yaml = "0.8.24"
tokio = { version = "1.21.0", features = ["full"] }

pont-config = { path = "../../config" }
pont-crypto = { path = "../../crates/pont-crypto" }
pont-logger = { path = "../../crates/pont-logger" }
pont-metrics-core = { path = "../../crates/pont-metrics-core" }
pont-secure-storage = { path = "../../secure/storage" }
pont-time-service = { path = "../../crates/pont-time-service" }
pont-types = { path = "../../types" }

channel = { path = "../../crates/channel" }
event-notifications = { path = "../../state-sync/inter-component/event-notifications" }
network = { path = "../../network" }
short-hex-str = { path = "../../crates/short-hex-str" }

[dev-dependencies]
rand = "0.7.3"

pont-config = { path = "../../config", features = ["testing"] }
pont-temppath = { path = "../../crates/pont-temppath" }
netcore = { path = "../netcore", features = ["fuzzing"] }
