[package]
name = "consensus-notifications"
version = "0.1.0"
authors = ["Pont Labs <opensource@pontlabs.com>"]
repository = "https://github.com/aptos-labs/pont-core"
description = "The notification interface between state sync and consensus"
homepage = "https://pontlabs.com"
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
async-trait = "0.1.53"
futures = "0.3.21"
serde = { version = "1.0.137", default-features = false }
thiserror = "1.0.31"
tokio = { version = "1.21.0" }

pont-crypto = { path = "../../../crates/pont-crypto" }
pont-types = { path = "../../../types" }

[dev-dependencies]
claims = "0.7"

move-core-types = { workspace = true }
