[package]
name = "MarketPlace"
version = "0.0.1"

[dependencies]
AptosFramework = { local = "../../framework/pont-framework" }
AptosToken = { local = "../../framework/pont-token" }

[addresses]
std = "0x1"
marketplace = "_"