[package]
name = "pont-node-checker"
version = "0.1.1"
description = "Pont Node Health Checker"
authors = ["Pont Labs <opensource@pontlabs.com>"]
edition = "2021"
repository = "https://github.com/aptos-labs/pont-core"
homepage = "https://pontlabs.com"
license = "Apache-2.0"
publish = false

[dependencies]
anyhow = "1.0.57"
async-trait = "0.1.53"
clap = { version = "3.1.17", features = ["derive"] }
const_format = "0.2.26"
env_logger = "0.8.4"
futures = "0.3.21"
log = "0.4"
once_cell = "1.10.0"
poem = { version = "1.3.40", features = ["anyhow"] }
poem-openapi = { version = "2.0.10", features = ["swagger-ui", "url"] }
prometheus-parse = "0.2.2"
reqwest = { version = "0.11.10", features = ["cookies"] }
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"
serde_yaml = "0.8.24"
thiserror = "1.0.31"
tokio = { version = "1.21.0", features = ["full"] }
url = { version = "2.2.2", features = ["serde"] }

pont-api = { path = "../../api" }
pont-config = { path = "../../config" }
pont-crypto = { path = "../../crates/pont-crypto" }
pont-logger = { path = "../../crates/pont-logger" }
pont-network-checker = { path = "../../crates/pont-network-checker" }
pont-rest-client = { path = "../../crates/pont-rest-client" }
pont-sdk = { path = "../../sdk" }

transaction-emitter-lib = { path = "../../crates/transaction-emitter-lib" }

[lib]
name = "pont_node_checker_lib"
path = "src/lib.rs"
