[package]
name = "data-streaming-service"
version = "0.1.0"
authors = ["Pont Labs <opensource@pontlabs.com>"]
repository = "https://github.com/aptos-labs/pont-core"
description = "The data streaming service that sends data notifications to clients"
homepage = "https://pontlabs.com"
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
async-trait = "0.1.53"
enum_dispatch = "0.3.8"
futures = "0.3.21"
once_cell = "1.10.0"
serde = { version = "1.0.137", default-features = false }
thiserror = "1.0.31"
tokio = { version = "1.21.0", features = ["full"] }
tokio-stream = "0.1.8"

pont-config = { path = "../../../config" }
pont-crypto = { path = "../../../crates/pont-crypto" }
pont-data-client = { path = "../../pont-data-client" }
pont-id-generator = { path = "../../../crates/pont-id-generator" }
pont-infallible = { path = "../../../crates/pont-infallible" }
pont-logger = { path = "../../../crates/pont-logger" }
pont-metrics-core = { path = "../../../crates/pont-metrics-core" }
pont-types = { path = "../../../types" }

channel = { path = "../../../crates/channel" }
network = { path = "../../../network" }
short-hex-str = { path = "../../../crates/short-hex-str" }

[dev-dependencies]
claims = "0.7"
rand = "0.7.3"
tokio = { version = "1.21.0", features = ["full"] }

pont-types = { path = "../../../types" }
storage-service-types = { path = "../../storage-service/types" }
