[package]
name = "move-examples"
version = "0.1.0"
authors = ["Pont Labs <opensource@pontlabs.com>"]
repository = "https://github.com/pont-core/aptos-labs"
homepage = "https://pontlabs.com"
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
pont-gas = { path = "../pont-gas" }
clap = "3.1.8"

pont-types = { path = "../../types" }
pont-vm = { path = "../pont-vm", features = ["testing"] }

move-cli = { workspace = true }
move-package = { workspace = true }
move-prover = { workspace = true }
move-unit-test = { workspace = true }
move-vm-runtime = { workspace = true }

[dev-dependencies]
tempfile = "3.3.0"
