[package]
name = "storage-service-server"
version = "0.1.0"
authors = ["Pont Labs <opensource@pontlabs.com>"]
description = "The Pont storage service (server-side)"
repository = "https://github.com/aptos-labs/pont-core"
homepage = "https://pontlabs.com"
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
bcs = { git = "https://github.com/aptos-labs/bcs", rev = "2cde3e8446c460cb17b0c1d6bac7e27e964ac169" }
bytes = "1.1.0"
futures = "0.3.21"
lru = "0.7.5"
once_cell = "1.10.0"
serde = { version = "1.0.137", default-features = false }
thiserror = "1.0.31"
tokio = { version = "1.21.0", features = ["rt", "macros"], default-features = false }

pont-config = { path = "../../../config" }
pont-infallible = { path = "../../../crates/pont-infallible" }
pont-logger = { path = "../../../crates/pont-logger" }
pont-metrics-core = { path = "../../../crates/pont-metrics-core" }
pont-time-service = { path = "../../../crates/pont-time-service", features = ["async"] }
pont-types = { path = "../../../types" }

bounded-executor = { path = "../../../crates/bounded-executor" }
channel = { path = "../../../crates/channel" }
network = { path = "../../../network" }
storage-interface = { path = "../../../storage/storage-interface" }
storage-service-types = { path = "../types" }

[dev-dependencies]
anyhow = "1.0.57"
claims = "0.7"
mockall = "0.11.0"
rand = "0.7.3"

pont-bitvec = { path = "../../../crates/pont-bitvec" }
pont-crypto = { path = "../../../crates/pont-crypto" }
pont-time-service = { path = "../../../crates/pont-time-service", features = ["async", "testing"] }
pont-types = { path = "../../../types" }
storage-interface = { path = "../../../storage/storage-interface" }
