[package]
name = "cached-packages"
version = "0.1.0"
edition = "2021"
authors = ["Pont Labs <opensource@pontlabs.com>"]
description = "Builds framework packages for caching in builds and tests"
repository = "https://github.com/aptos-labs/pont-core"
homepage = "https://pontlabs.com"
license = "Apache-2.0"
publish = false

[dependencies]
pont-types = { path = "../../../types" }
bcs = { git = "https://github.com/aptos-labs/bcs", rev = "2cde3e8446c460cb17b0c1d6bac7e27e964ac169" }
framework = { path = ".." }
include_dir = { version = "0.7.2", features = ["glob"] }
once_cell = "1.10.0"
proptest = { version = "1.0.0", optional = true }
proptest-derive = { version = "0.3.0", optional = true }

move-core-types = { workspace = true }

[build-dependencies]
framework = { path = ".." }

[features]
default = []
fuzzing = ["proptest", "proptest-derive"]
