[package]
name = "generate-format"
version = "0.1.0"
authors = ["Pont Labs <opensource@pontlabs.com>"]
description = "Pont core type checker to ensure compatibility"
repository = "https://github.com/aptos-labs/pont-core"
homepage = "https://pontlabs.com"
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
bcs = { git = "https://github.com/aptos-labs/bcs", rev = "2cde3e8446c460cb17b0c1d6bac7e27e964ac169" }
rand = "0.7.3"
serde = { version = "1.0.137", features = ["derive"] }
serde-reflection = { git = "https://github.com/aptos-labs/serde-reflection", rev = "839aed62a20ddccf043c08961cfe74875741ccba" }
serde_yaml = "0.8.24"
structopt = "0.3.21"

pont-api-types = { path = "../../api/types", package = "pont-api-types" }
pont-config = { path = "../../config" }
pont-crypto = { path = "../../crates/pont-crypto", features = ["fuzzing"] }
pont-crypto-derive = { path = "../../crates/pont-crypto-derive" }
pont-types = { path = "../../types", features = ["fuzzing"] }

consensus = { path = "../../consensus", features = ["fuzzing"] }
consensus-types = { path = "../../consensus/consensus-types", features = ["fuzzing"] }
move-core-types = { workspace = true, features = ["fuzzing"] }
network = { path = "../../network" }

[[bin]]
name = "compute"
path = "src/compute.rs"
test = false
