[package]
name = "storage-interface"
version = "0.1.0"
authors = ["Pont Labs <opensource@pontlabs.com>"]
description = "Pont storage interface"
repository = "https://github.com/aptos-labs/pont-core"
homepage = "https://pontlabs.com"
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
anyhow = "1.0.57"
bcs = { git = "https://github.com/aptos-labs/bcs", rev = "2cde3e8446c460cb17b0c1d6bac7e27e964ac169" }
crossbeam-channel = "0.5.4"
once_cell = "1.10.0"
parking_lot = "0.12.0"
rayon = "1.5.2"
serde = { version = "1.0.137", default-features = false }
thiserror = "1.0.31"

pont-crypto = { path = "../../crates/pont-crypto" }
pont-logger = { path = "../../crates/pont-logger" }
pont-metrics-core = { path = "../../crates/pont-metrics-core" }
pont-secure-net = { path = "../../secure/net" }
pont-state-view = { path = "../state-view" }
pont-types = { path = "../../types" }
pont-vm = { path = "../../pont-move/pont-vm" }

scratchpad = { path = "../scratchpad" }

move-core-types = { workspace = true }

[dev-dependencies]
assert_unordered = "0.1.1"

pont-types = { path = "../../types", features = ["fuzzing"] }

[features]
default = []
fuzzing = ["pont-types/fuzzing"]
