[package]
name = "executor-types"
version = "0.1.0"
authors = ["Pont Labs <opensource@pontlabs.com>"]
description = "Pont executor interface types"
repository = "https://github.com/aptos-labs/pont-core"
homepage = "https://pontlabs.com"
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
anyhow = "1.0.57"
bcs = { git = "https://github.com/aptos-labs/bcs", rev = "2cde3e8446c460cb17b0c1d6bac7e27e964ac169" }
itertools = "0.10.0"
once_cell = "1.10.0"
serde = { version = "1.0.137", default-features = false }
thiserror = "1.0.31"

pont-crypto = { path = "../../crates/pont-crypto" }
pont-secure-net = { path = "../../secure/net" }
pont-state-view = { path = "../../storage/state-view" }
pont-types = { path = "../../types" }

scratchpad = { path = "../../storage/scratchpad" }
storage-interface = { path = "../../storage/storage-interface" }

[features]
default = []
fuzzing = ["pont-crypto/fuzzing", "pont-types/fuzzing"]
