[package]
name = "pont-rosetta"
version = "0.0.1"
description = "Pont Rosetta"
authors = ["Pont Labs <opensource@pontlabs.com>"]
edition = "2021"
repository = "https://github.com/aptos-labs/pont-core"
homepage = "https://pontlabs.com"
license = "Apache-2.0"
publish = false

[dependencies]
anyhow = "1.0.57"
pont-config = { path = "../../config" }
pont-crypto = { path = "../pont-crypto" }
pont-global-constants = { path = "../../config/global-constants" }
pont-logger = { path = "../pont-logger" }
pont-node = { path = "../../pont-node" }
pont-rest-client = { path = "../pont-rest-client" }
pont-sdk = { path = "../../sdk" }
pont-types = { path = "../../types" }
pont-warp-webserver = { path = "../pont-warp-webserver" }
bcs = { git = "https://github.com/aptos-labs/bcs", rev = "2cde3e8446c460cb17b0c1d6bac7e27e964ac169" }
cached-packages = { path = "../../pont-move/framework/cached-packages" }
clap = "3.1.18"
futures = "0.3.17"
hex = "0.4.3"
itertools = "0.10.3"
once_cell = "1.10.0"
percent-encoding = "2.1.0"
reqwest = { version = "0.11.10", features = ["json", "cookies"] }
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"
serde_yaml = "0.8.24"
tokio = { version = "1.21.0", features = ["full", "time"] }
url = "2.2.2"
warp = "0.3.2"

move-deps = { path = "../../pont-move/move-deps" }
