[package]
name = "pont-github-client"
version = "0.1.0"
authors = ["Pont Labs <opensource@pontlabs.com>"]
repository = "https://github.com/aptos-labs/pont-core"
description = "Pont's Restful GitHub Client"
homepage = "https://pontlabs.com"
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
serde = { version = "1.0.137", features = ["derive"], default-features = false }
serde_json = "1.0.81"
thiserror = "1.0.31"
ureq = { version = "1.5.4", features = ["json", "native-tls"], default-features = false }

proxy = { path = "../../../crates/proxy" }

[dev-dependencies]
base64 = "0.13.0"
