[package]
name = "memsocket"
version = "0.1.0"
authors = ["Pont Labs <opensource@pontlabs.com>"]
description = "Pont memsocket"
repository = "https://github.com/aptos-labs/pont-core"
homepage = "https://pontlabs.com"
license = "Apache-2.0"
edition = "2021"
publish = false

[dependencies]
bytes = "1.1.0"
futures = "0.3.21"
once_cell = "1.10.0"

pont-infallible = { path = "../../crates/pont-infallible" }

[features]
default = []
fuzzing = []
testing = []
