[package]
name = "pont-rate-limiter"
version = "0.1.0"
authors = ["Pont Labs <opensource@pontlabs.com>"]
description = "Token bucket rate limiter"
repository = "https://github.com/aptos-labs/pont-core"
homepage = "https://pontlabs.com"
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
futures = "0.3.21"
pin-project = "1.0.10"
tokio = { version = "1.21.0", features = ["full"] }
tokio-util = { version = "0.7.2", features = ["compat"] }

pont-infallible = { path = "../../crates/pont-infallible" }
pont-logger = { path = "../../crates/pont-logger" }
pont-metrics-core = { path = "../../crates/pont-metrics-core" }

