[package]
name = "pont-substreams"
version = "0.0.1"
description = "Substreams for Pont Chain"
authors = ["Pont Labs <opensource@pontlabs.com>"]
repository = "https://github.com/aptos-labs/pont-core"
homepage = "https://pontlabs.com"
license = "Apache-2.0"
publish = false
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.57"
serde = { version = "1.0.137", default-features = false }
serde_json = "1.0.81"
substreams = "0.0.17"

pont-protos = { path = "../../../crates/pont-protos" }

# This is the difference between a multi MB binary, and a few hundred KB binary
[profile.release]
lto = true
opt-level = 's'
strip = "debuginfo"
