apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "pont-fullnode.fullname" . }}-e{{ .Values.chain.era }}
  labels:
    {{- include "pont-fullnode.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: {{ .Values.storage.class }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}
