[package]
name = "peer-monitoring-service-client"
version = "0.1.0"
authors = ["Pont Labs <opensource@pontlabs.com>"]
description = "The Pont peer monitoring service (client-side)"
repository = "https://github.com/aptos-labs/pont-core"
homepage = "https://pontlabs.com"
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
async-trait = "0.1.42"
thiserror = "1.0.24"

pont-config = { path = "../../../config" }
pont-types = { path = "../../../types" }

channel = { path = "../../../crates/channel" }
network = { path = "../../../network" }
peer-monitoring-service-types = { path = "../types" }
