[package]
name = "pont-telemetry"
version = "0.1.0"
authors = ["Pont Labs <opensource@pontlabs.com>"]
description = "Pont utilities to collect observability data from a node and send it to a remote destination"
repository = "https://github.com/aptos-labs/pont-core"
homepage = "https://pontlabs.com"
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
anyhow = "1.0.57"
pont-crypto = { path = "../../crates/pont-crypto" }
pont-telemetry-service = { path = "../../crates/pont-telemetry-service" }
pont-types = { path = "../../types" }
flate2 = "1.0"
futures = "0.3.21"
once_cell = "1.10.0"
prometheus = { version = "0.13.1", default-features = false }
rand = "0.7.3"
rand_core = "0.5.1"
reqwest = { version = "0.11.10", features = ["json"] }
reqwest-middleware = { version = "0.1.6" }
reqwest-retry = { version = "0.1.5" }
serde = { version = "1.0.137", features = ["derive"], default-features = false }
serde_json = "1.0.81"
sysinfo = "0.24.2"
thiserror = "1.0.32"
tokio = { version = "1.21.0" }
tokio-retry = "0.3"
tokio-stream = "0.1.8"
url = "2.2.2"
uuid = { version = "1.0.0", features = ["v4", "serde"] }

pont-api = { path = "../../api" }
pont-config = { path = "../../config" }
pont-infallible = { path = "../../crates/pont-infallible" }
pont-logger = { path = "../../crates/pont-logger" }
pont-mempool = { path = "../../mempool" }
pont-metrics-core = { path = "../../crates/pont-metrics-core" }
pontdb = { path = "../../storage/pontdb" }
consensus = { path = "../../consensus" }
network = { path = "../../network" }
node-resource-metrics = { path = "../../crates/node-resource-metrics" }
state-sync-driver = { path = "../../state-sync/state-sync-v2/state-sync-driver" }

[dev-dependencies]
httpmock = "0.6"
