[package]
name = "pont-gas"
version = "0.1.0"
authors = ["Pont Labs <opensource@pontlabs.com>"]
description = "Gas metering for the Pont blockchain"
repository = "https://github.com/aptos-labs/pont-core"
homepage = "https://pontlabs.com"
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
anyhow = "1.0.57"
bcs = { git = "https://github.com/aptos-labs/bcs", rev = "2cde3e8446c460cb17b0c1d6bac7e27e964ac169" }
clap = { version = "3.1.17", features = ["derive"] }

move-binary-format = { workspace = true }
move-core-types = { workspace = true }
move-model = { workspace = true }
move-stdlib = { workspace = true }
move-table-extension = { workspace = true }
move-vm-types = { workspace = true }

pont-global-constants = { path = "../../config/global-constants" }
pont-types = { path = "../../types" }
framework = { path = "../framework" }
gas-algebra-ext = { path = "../gas-algebra-ext" }
package-builder = { path = "../package-builder" }

[dev-dependencies]
tempfile = "3.3.0"

[features]
testing = ["move-stdlib/testing", "pont-global-constants/testing"]

[[bin]]
name = "pont-gas-gen-update-proposal"
path = "src/bin/gen_proposal.rs"
