[package]
name = "pont-fuzzer"
version = "0.1.0"
authors = ["Pont Labs <opensource@pontlabs.com>"]
description = "Pont fuzzer"
repository = "https://github.com/aptos-labs/pont-core"
homepage = "https://pontlabs.com"
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
anyhow = "1.0.57"
bcs = { git = "https://github.com/aptos-labs/bcs", rev = "2cde3e8446c460cb17b0c1d6bac7e27e964ac169" }
byteorder = { version = "1.4.3", default-features = false }
hex = "0.4.3"
once_cell = "1.10.0"
proptest = { version = "1.0.0", default-features = false }
proptest-derive = { version = "0.3.0", default-features = false }
rand = "0.7.3"
rusty-fork = { version = "0.3.0", default-features = false }
sha-1 = { version = "0.10.0", default-features = false }
structopt = "0.3.21"

accumulator = { path = "../../storage/accumulator", features = ["fuzzing"] }
pont-crypto = { path = "../../crates/pont-crypto", features = ["fuzzing"] }
pont-jellyfish-merkle = { path = "../../storage/jellyfish-merkle", features = ["fuzzing"] }
pont-mempool = { path = "../../mempool" }
pont-proptest-helpers = { path = "../../crates/pont-proptest-helpers" }
pont-types = { path = "../../types", features = ["fuzzing"] }
pont-vault-client = { path = "../../secure/storage/vault", features = ["fuzzing"] }

pontdb = { path = "../../storage/pontdb", features = ["fuzzing"] }
consensus = { path = "../../consensus", features = ["fuzzing"] }
consensus-types = { path = "../../consensus/consensus-types", features = ["fuzzing"] }
executor = { path = "../../execution/executor", features = ["fuzzing"] }
executor-types = { path = "../../execution/executor-types", features = ["fuzzing"] }
language-e2e-tests = { path = "../../pont-move/e2e-tests" }
move-binary-format = { workspace = true, features = ["fuzzing"] }
move-core-types = { workspace = true, features = ["fuzzing"] }
move-vm-types = { workspace = true }
network = { path = "../../network", features = ["fuzzing"] }
safety-rules = { path = "../../consensus/safety-rules", features = ["fuzzing", "testing"] }
scratchpad = { path = "../../storage/scratchpad", features = ["fuzzing"] }
storage-interface = { path = "../../storage/storage-interface" }

[dev-dependencies]
datatest-stable = "0.1.1"
rusty-fork = "0.3.0"
stats_alloc = "0.1.8"

[[test]]
harness = false
name = "artifacts"
