[package]
name = "AptosFramework"
version = "1.0.0"

[addresses]
std = "0x1"
pont_std = "0x1"
aptos_framework = "0x1"
aptos_token = "0x3"
core_resources = "0xA550C18"
vm_reserved = "0x0"

[dependencies]
PontStdlib = { local = "../pont-stdlib" }
MoveStdlib = { local = "../move-stdlib" }
