[package]
name = "pont-rocksdb-options"
version = "0.1.0"
authors = ["Pont Labs <opensource@pontlabs.com>"]
description = "Pont RocksDb Options"
repository = "https://github.com/aptos-labs/pont-core"
homepage = "https://pontlabs.com"
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
pont-config = { path = "../../config" }

rocksdb = { version = "0.19.0", default-features = false, features = ["lz4"] }
