[package]
name = "peer-monitoring-service-server"
version = "0.1.0"
authors = ["Pont Labs <opensource@pontlabs.com>"]
description = "The peer monitoring service (server-side)"
repository = "https://github.com/aptos-labs/pont-core"
homepage = "https://pontlabs.com"
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
bcs = { git = "https://github.com/aptos-labs/bcs", rev = "2cde3e8446c460cb17b0c1d6bac7e27e964ac169" }
bytes = "1.0.1"
futures = "0.3.12"
once_cell = "1.7.2"
serde = { version = "1.0.124", default-features = false }
thiserror = "1.0.24"
tokio = { version = "1.8.1", features = ["rt", "macros"], default-features = false }

pont-config = { path = "../../../config" }
pont-logger = { path = "../../../crates/pont-logger" }
pont-metrics-core = { path = "../../../crates/pont-metrics-core" }
pont-types = { path = "../../../types" }

bounded-executor = { path = "../../../crates/bounded-executor" }
channel = { path = "../../../crates/channel" }
netcore = { path = "../../netcore" }
network = { path = "../../../network" }
peer-monitoring-service-types = { path = "../types" }
