[package]
name = "accumulator"
version = "0.1.0"
authors = ["Pont Labs <opensource@pontlabs.com>"]
description = "Pont merkle tree accumulator"
repository = "https://github.com/aptos-labs/pont-core"
homepage = "https://pontlabs.com"
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
anyhow = "1.0.57"
proptest = { version = "1.0.0", optional = true }

pont-crypto = { path = "../../crates/pont-crypto" }
pont-types = { path = "../../types" }

[dev-dependencies]
proptest = "1.0.0"
rand = "0.7.3"

pont-crypto = { path = "../../crates/pont-crypto", features = ["fuzzing"] }

[features]
default = []
fuzzing = ["proptest", "pont-crypto/fuzzing", "pont-types/fuzzing"]
