[package]
name = "executor-benchmark"
version = "0.1.0"
authors = ["Pont Labs <opensource@pontlabs.com>"]
description = "Pont executor benchmark"
repository = "https://github.com/aptos-labs/pont-core"
homepage = "https://pontlabs.com"
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
chrono = "0.4.19"
criterion = "0.3.5"
indicatif = "0.15.0"
itertools = "0.10.3"
num_cpus = "1.13.1"
rand = "0.7.3"
rayon = "1.5.2"
serde = "1.0.137"
structopt = "0.3.21"
toml = "0.5.9"

pont-config = { path = "../../config" }
pont-crypto = { path = "../../crates/pont-crypto" }
pont-genesis = { path = "../../crates/pont-genesis", features = ["testing"] }
pont-infallible = { path = "../../crates/pont-infallible" }
pont-jellyfish-merkle = { path = "../../storage/jellyfish-merkle" }
pont-logger = { path = "../../crates/pont-logger" }
pont-push-metrics = { path = "../../crates/pont-push-metrics" }
pont-sdk = { path = "../../sdk" }
pont-state-view = { path = "../../storage/state-view" }
pont-types = { path = "../../types" }
pont-vm = { path = "../../pont-move/pont-vm" }

pontdb = { path = "../../storage/pontdb" }
executor = { path = "../executor" }
executor-types = { path = "../executor-types" }
schemadb = { path = "../../storage/schemadb" }
scratchpad = { path = "../../storage/scratchpad" }
storage-interface = { path = "../../storage/storage-interface" }

[target.'cfg(unix)'.dependencies]
jemallocator = { version = "0.3.2", features = ["profiling", "unprefixed_malloc_on_supported_platforms"] }

[dev-dependencies]
pont-temppath = { path = "../../crates/pont-temppath" }

[features]
default = []
fuzzing = ["pont-config/fuzzing", "pont-crypto/fuzzing", "pont-types/fuzzing"]

[[bench]]
name = "executor_benchmark"
harness = false
