[package]
name = "event-notifications"
version = "0.1.0"
authors = ["Pont Labs <opensource@pontlabs.com>"]
repository = "https://github.com/aptos-labs/pont-core"
description = "The notification service offered by state sync for on-chain events"
homepage = "https://pontlabs.com"
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
async-trait = "0.1.53"
futures = "0.3.21"
serde = { version = "1.0.137", default-features = false }
thiserror = "1.0.31"

pont-id-generator = { path = "../../../crates/pont-id-generator" }
pont-infallible = { path = "../../../crates/pont-infallible" }
pont-state-view = { path = "../../../storage/state-view" }
pont-types = { path = "../../../types" }

channel = { path = "../../../crates/channel" }
storage-interface = { path = "../../../storage/storage-interface" }

[dev-dependencies]
bcs = { git = "https://github.com/aptos-labs/bcs", rev = "2cde3e8446c460cb17b0c1d6bac7e27e964ac169" }
claims = "0.7"

pont-crypto = { path = "../../../crates/pont-crypto" }
pont-temppath = { path = "../../../crates/pont-temppath" }
pont-vm = { path = "../../../pont-move/pont-vm" }
pontdb = { path = "../../../storage/pontdb" }
executor-test-helpers = { path = "../../../execution/executor-test-helpers" }
move-deps = { path = "../../../pont-move/move-deps", features = ["address32"] }
vm-genesis = { path = "../../../pont-move/vm-genesis", features = ["fuzzing"] }
