[package]
name = "schemadb"
version = "0.1.0"
authors = ["Pont Labs <opensource@pontlabs.com>"]
description = "Pont schemadb"
repository = "https://github.com/aptos-labs/pont-core"
homepage = "https://pontlabs.com"
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
anyhow = "1.0.57"
once_cell = "1.10.0"
proptest = { version = "1.0.0", optional = true }
rocksdb = { version = "0.19.0", default-features = false, features = ["lz4"] }

pont-infallible = { path = "../../crates/pont-infallible" }
pont-logger = { path = "../../crates/pont-logger" }
pont-metrics-core = { path = "../../crates/pont-metrics-core" }

[dev-dependencies]
byteorder = "1.4.3"
proptest = "1.0.0"

pont-temppath = { path = "../../crates/pont-temppath" }

[features]
fuzzing = ["proptest"]
