[package]
name = "testcases"
version = "0.0.0"
authors = ["Pont Labs <opensource@pontlabs.com>"]
description = "Pont compatibility tests"
repository = "https://github.com/aptos-labs/pont-core"
homepage = "https://pontlabs.com"
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
anyhow = "1.0.57"
pont = { path = "../../crates/pont", features = ["fuzzing"] }

pont-genesis = { path = "../../crates/pont-genesis", features = ["testing"] }
pont-global-constants = { path = "../../config/global-constants" }
pont-keygen = { path = "../../crates/pont-keygen" }
pont-logger = { path = "../../crates/pont-logger" }
pont-rest-client = { path = "../../crates/pont-rest-client" }
pont-sdk = { path = "../../sdk" }
pont-types = { path = "../../types" }

forge = { path = "../forge" }
futures = "0.3.21"
hex = "0.4.3"
move-examples = { path = "../../pont-move/move-examples" }
rand = "0.7.3"
reqwest = { version = "0.11.10", features = ["json", "cookies", "blocking"] }
serde_json = "1.0.81"
tokio = { version = "1.21.0", features = ["full"] }

[[test]]
name = "forge-local-compatibility"
harness = false

[[test]]
name = "forge-local-performance"
harness = false
