[package]
name = "executor-test-helpers"
version = "0.1.0"
authors = ["Pont Labs <opensource@pontlabs.com>"]
description = "Pont executor test helpers"
repository = "https://github.com/aptos-labs/pont-core"
homepage = "https://pontlabs.com"
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
anyhow = "1.0.57"
rand = "0.7.3"

pont-config = { path = "../../config" }
pont-crypto = { path = "../../crates/pont-crypto" }
pont-genesis = { path = "../../crates/pont-genesis", features = ["testing"] }
pont-sdk = { path = "../../sdk" }
pont-state-view = { path = "../../storage/state-view" }
pont-temppath = { path = "../../crates/pont-temppath" }
pont-types = { path = "../../types", features = ["fuzzing"] }
pont-vm = { path = "../../pont-move/pont-vm" }
pontdb = { path = "../../storage/pontdb", features = ["fuzzing"] }
cached-packages = { path = "../../pont-move/framework/cached-packages" }
consensus-types = { path = "../../consensus/consensus-types" }
executor = { path = "../executor" }
executor-types = { path = "../executor-types" }
storage-interface = { path = "../../storage/storage-interface" }
vm-genesis = { path = "../../pont-move/vm-genesis" }
