[package]
name = "scratchpad"
version = "0.1.0"
authors = ["Pont Labs <opensource@pontlabs.com>"]
description = "Pont scratchpad"
repository = "https://github.com/aptos-labs/pont-core"
homepage = "https://pontlabs.com"
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
bitvec = { version = "0.19.4" }
criterion = { version = "0.3.6", optional = true }
itertools = "0.10.0"
once_cell = "1.10.0"
proptest = { version = "1.0.0", optional = true }
rayon = "1.5.2"
thiserror = "1.0.24"

pont-crypto = { path = "../../crates/pont-crypto" }
pont-infallible = { path = "../../crates/pont-infallible" }
pont-metrics-core = { path = "../../crates/pont-metrics-core" }
pont-types = { path = "../../types" }

[dev-dependencies]
bitvec = "0.19.4"
once_cell = "1.10.0"
proptest = "1.0.0"
rand = "0.7.3"

pont-types = { path = "../../types", features = ["fuzzing"] }

[features]
fuzzing = ["pont-types/fuzzing", "proptest"]
bench = ["proptest", "criterion"]

[[bench]]
name = "sparse_merkle"
harness = false
required-features = ["bench"]

[lib]
# Allow Criterion benchmarks to take command line arguments
# https://bheisler.github.io/criterion.rs/book/faq.html#cargo-bench-gives-unrecognized-option-errors-for-valid-command-line-options
bench = false
