[package]
name = "pont-sf-indexer"
version = "0.0.1"
description = "Pont Indexer"
authors = ["Pont Labs <opensource@pontlabs.com>"]
edition = "2021"
repository = "https://github.com/aptos-labs/pont-core"
homepage = "https://pontlabs.com"
license = "Apache-2.0"
publish = false

[dependencies]
anyhow = "1.0.57"

pont-crypto = { path = "../../../crates/pont-crypto" }
pont-logger = { path = "../../../crates/pont-logger" }
pont-metrics-core = { path = "../../../crates/pont-metrics-core" }
pont-protos = { path = "../../../crates/pont-protos" }
pont-rest-client = { path = "../../../crates/pont-rest-client" }
pont-types = { path = "../../../types" }
inspection-service = { path = "../../../crates/inspection-service" }

async-stream = "0.3"
async-trait = "0.1.53"
bigdecimal = { version = "0.3.0", features = ["serde"] }
bytes = "1.1.0"
chrono = { version = "0.4.19", default-features = false, features = ["clock", "serde"] }
clap = "3.1.17"
diesel = { version = "1.4.8", features = ["chrono", "postgres", "r2d2", "numeric", "serde_json"] }
diesel_migrations = { version = "1.4.0", features = ["postgres"] }
field_count = "0.1.1"
futures = "0.3.21"
http = "0.2.3"
hyper = { version = "0.14.18", features = ["full"] }
once_cell = "1.10.0"
pbjson = "0.4.0"
prost = "0.10.4"
prost-types = "0.10.1"
reqwest = { version = "0.11.10", features = ["json", "cookies"] }
reqwest-middleware = { version = "0.1.6" }
reqwest-retry = { version = "0.1.5" }
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"
tokio = { version = "1.21.0", features = ["full", "time"] }
tokio-retry = "0.3.0"
tonic = { version = "0.7.2", features = ["tls-roots", "transport", "prost", "compression", "codegen"] }
url = "2.2.2"

[[bin]]
name = "pont-sf-indexer"
