[package]
name = "pontdb-indexer"
version = "0.1.0"
authors = ["Pont Labs <opensource@pontlabs.com>"]
description = "PontDB Internal Indexer"
repository = "https://github.com/aptos-labs/pont-core"
homepage = "https://pontlabs.com"
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
anyhow = "1.0.57"
bcs = { git = "https://github.com/aptos-labs/bcs", rev = "2cde3e8446c460cb17b0c1d6bac7e27e964ac169" }
byteorder = "1.4.3"
num-derive = "0.3.3"
proptest = { version = "1.0.0", optional = true }
proptest-derive = { version = "0.3.0", optional = true }
serde = "1.0.137"

pont-config = { path = "../../config" }
pont-crypto = { path = "../../crates/pont-crypto" }
pont-infallible = { path = "../../crates/pont-infallible" }
pont-logger = { path = "../../crates/pont-logger" }
pont-metrics-core = { path = "../../crates/pont-metrics-core" }
pont-proptest-helpers = { path = "../../crates/pont-proptest-helpers", optional = true }
pont-rocksdb-options = { path = "../rocksdb-options" }
pont-state-view = { path = "../state-view" }
pont-temppath = { path = "../../crates/pont-temppath", optional = true }
pont-types = { path = "../../types" }
pont-vm = { path = "../../pont-move/pont-vm" }
schemadb = { path = "../schemadb" }
scratchpad = { path = "../scratchpad" }
storage-interface = { path = "../storage-interface" }

move-core-types = { git = "https://github.com/move-language/move", rev = "6a32284d6e04ea5bfa5919df9aac2ccb3ffa010e", features = ["address32"] }
move-resource-viewer = { git = "https://github.com/move-language/move", rev = "6a32284d6e04ea5bfa5919df9aac2ccb3ffa010e" }

[dev-dependencies]
proptest = "1.0.0"
proptest-derive = "0.3.0"
rand = "0.7.3"

pont-proptest-helpers = { path = "../../crates/pont-proptest-helpers" }
pont-types = { path = "../../types", features = ["fuzzing"] }
schemadb = { path = "../schemadb", features = ["fuzzing"] }

[features]
default = []
fuzzing = ["proptest", "proptest-derive", "pont-proptest-helpers", "pont-temppath", "pont-crypto/fuzzing", "pont-types/fuzzing", "schemadb/fuzzing", "scratchpad/fuzzing"]
