[package]
name = "network-builder"
version = "0.1.0"
authors = ["Pont Labs <opensource@pontlabs.com>"]
description = "Pont network builder for constructing a network"
repository = "https://github.com/aptos-labs/pont-core"
homepage = "https://pontlabs.com"
license = "Apache-2.0"
publish = false
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.53"
bcs = { git = "https://github.com/aptos-labs/bcs", rev = "2cde3e8446c460cb17b0c1d6bac7e27e964ac169" }
futures = "0.3.21"
rand = "0.7.3"
serde = { version = "1.0.137", default-features = false }
tokio = { version = "1.21.0", features = ["full"] }

pont-config = { path = "../../config" }
pont-crypto = { path = "../../crates/pont-crypto" }
pont-infallible = { path = "../../crates/pont-infallible" }
pont-logger = { path = "../../crates/pont-logger" }
pont-secure-storage = { path = "../../secure/storage" }
pont-time-service = { path = "../../crates/pont-time-service", features = ["async"] }
pont-types = { path = "../../types" }

channel = { path = "../../crates/channel" }
event-notifications = { path = "../../state-sync/inter-component/event-notifications" }
netcore = { path = "../netcore" }
network = { path = "../." }
network-discovery = { path = "../discovery" }
