[package]
name = "backup-cli"
version = "0.1.0"
authors = ["Pont Labs <opensource@pontlabs.com>"]
repository = "https://github.com/aptos-labs/pont-core"
homepage = "https://pontlabs.com"
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
anyhow = "1.0.57"
async-trait = "0.1.53"
bcs = { git = "https://github.com/aptos-labs/bcs", rev = "2cde3e8446c460cb17b0c1d6bac7e27e964ac169" }
bytes = "1.1.0"
clap = { version = "3.1.8", features = ["derive"] }
futures = "0.3.21"
itertools = "0.10.0"
num_cpus = "1.13.1"
once_cell = "1.10.0"
pin-project = "1.0.10"
rand = "0.7.3"
regex = "1.5.5"
reqwest = { version = "0.11.10", features = ["stream"], default-features = false }
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"
serde_yaml = "0.8.24"
tokio = { version = "1.21.0", features = ["full"] }
tokio-stream = "0.1.8"
tokio-util = { version = "0.7.2", features = ["compat"] }

pont-config = { path = "../../../config" }
pont-crypto = { path = "../../../crates/pont-crypto" }
pont-infallible = { path = "../../../crates/pont-infallible" }
pont-jellyfish-merkle = { path = "../../jellyfish-merkle" }
pont-logger = { path = "../../../crates/pont-logger" }
pont-push-metrics = { path = "../../../crates/pont-push-metrics" }
pont-temppath = { path = "../../../crates/pont-temppath" }
pont-types = { path = "../../../types" }
pont-vm = { path = "../../../pont-move/pont-vm" }

pontdb = { path = "../../pontdb" }
executor = { path = "../../../execution/executor" }
executor-test-helpers = { path = "../../../execution/executor-test-helpers", optional = true }
executor-types = { path = "../../../execution/executor-types" }
scratchpad = { path = "../../scratchpad" }
storage-interface = { path = "../../storage-interface" }

[dev-dependencies]
proptest = "1.0.0"
warp = "0.3.2"

pont-config = { path = "../../../config" }
pont-proptest-helpers = { path = "../../../crates/pont-proptest-helpers" }
pontdb = { path = "../../pontdb", features = ["fuzzing"] }
backup-service = { path = "../backup-service" }
executor-test-helpers = { path = "../../../execution/executor-test-helpers" }
storage-interface = { path = "../../storage-interface" }

[features]
fuzzing = ["pontdb/fuzzing"]
