[package]
name = "language-e2e-testsuite"
version = "0.1.0"
edition = "2021"
authors = ["Pont Labs <opensource@pontlabs.com>"]
description = "Move language e2e tests"
repository = "https://github.com/aptos-labs/pont-core"
homepage = "https://pontlabs.com"
license = "Apache-2.0"
publish = false

[dependencies]
bcs = { git = "https://github.com/aptos-labs/bcs", rev = "2cde3e8446c460cb17b0c1d6bac7e27e964ac169" }
itertools = "0.10.0"
proptest = "1.0.0"
serde = { version = "1.0.137", default-features = false }

pont-crypto = { path = "../../crates/pont-crypto", features = ["fuzzing"] }
pont-gas = { path = "../pont-gas", features = ["testing"] }
pont-keygen = { path = "../../crates/pont-keygen" }
pont-logger = { path = "../../crates/pont-logger" }
pont-parallel-executor = { path = "../parallel-executor" }
pont-state-view = { path = "../../storage/state-view" }
pont-types = { path = "../../types", features = ["fuzzing"] }
pont-vm = { path = "../pont-vm", features = ["fuzzing"] }
cached-packages = { path = "../framework/cached-packages" }
framework = { path = "../framework" }
vm-genesis = { path = "../vm-genesis" }

pont-writeset-generator = { path = "../writeset-transaction-generator" }
language-e2e-tests = { path = "../e2e-tests" }
move-binary-format = { workspace = true }
move-bytecode-verifier = { workspace = true }

move-core-types = { workspace = true }
move-ir-compiler = { workspace = true }

[features]
default = ["cached-packages/fuzzing"]
