[package]
name = "smoke-test"
version = "0.1.0"
authors = ["Pont Labs <opensource@pontlabs.com>"]
description = "Pont end to end tests"
repository = "https://github.com/aptos-labs/pont-core"
homepage = "https://pontlabs.com"
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
anyhow = "1.0.57"
async-trait = "0.1.53"
bcs = { git = "https://github.com/aptos-labs/bcs", rev = "2cde3e8446c460cb17b0c1d6bac7e27e964ac169" }
diesel = { version = "2.0.0", features = [
    "chrono",
    "postgres",
    "r2d2",
    "numeric",
    "serde_json",
] }
hex = "0.4.3"
proptest = "1.0.0"
reqwest = { version = "0.11.10", features = ["json"] }
serde_json = "1.0.81"
tokio = { version = "1.21.0", features = ["full"] }

pont = { path = "../../crates/pont", features = ["fuzzing"] }
pont-config = { path = "../../config" }
pont-crypto = { path = "../../crates/pont-crypto" }
pont-faucet = { path = "../../crates/pont-faucet" }
pont-gas = { path = "../../pont-move/pont-gas", features = ["testing"] }
pont-global-constants = { path = "../../config/global-constants", features = ["testing"] }
pont-indexer = { path = "../../crates/indexer" }
pont-keygen = { path = "../../crates/pont-keygen" }
pont-rest-client = { path = "../../crates/pont-rest-client" }
pont-rosetta = { path = "../../crates/pont-rosetta" }
pont-sdk = { path = "../../sdk" }
pont-temppath = { path = "../../crates/pont-temppath" }
pont-types = { path = "../../types" }
pont-vm = { path = "../../pont-move/pont-vm", features = ["fuzzing"] }
cached-packages = { path = "../../pont-move/framework/cached-packages" }
consensus = { path = "../../consensus" }
forge = { path = "../forge", features = ["testing"] }
framework = { path = "../../pont-move/framework" }
move-deps = { path = "../../pont-move/move-deps" }

[dev-dependencies]
base64 = "0.13.0"
futures = "0.3.21"
num_cpus = "1.13.1"
once_cell = "1.10.0"
rand = "0.7.3"
regex = "1.5.5"
serde_yaml = "0.8.24"

pont-genesis = { path = "../../crates/pont-genesis", features = ["testing"] }
pont-infallible = { path = "../../crates/pont-infallible" }
pont-logger = { path = "../../crates/pont-logger" }
pont-secure-storage = { path = "../../secure/storage", features = ["testing"] }
pont-time-service = { path = "../../crates/pont-time-service", features = ["testing"] }
pont-vault-client = { path = "../../secure/storage/vault", features = ["fuzzing"] }
pont-writeset-generator = { path = "../../pont-move/writeset-transaction-generator" }
backup-cli = { path = "../../storage/backup/backup-cli" }
