[package]
name = "forge-cli"
version = "0.0.0"
authors = ["Pont Labs <opensource@pontlabs.com>"]
description = "Pont end to end test framework CLI"
repository = "https://github.com/aptos-labs/pont-core"
homepage = "https://pontlabs.com"
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
anyhow = "1.0.57"
async-trait = "0.1.53"
structopt = "0.3.21"
tokio = { version = "1.21.0", features = ["full"] }
url = "2.2.2"

pont-global-constants = { path = "../../config/global-constants" }
pont-logger = { path = "../../crates/pont-logger" }
pont-rest-client = { path = "../../crates/pont-rest-client" }
pont-sdk = { path = "../../sdk" }
cached-packages = { path = "../../pont-move/framework/cached-packages" }
forge = { path = "../forge" }
framework = { path = "../../pont-move/framework" }
serde_yaml = "0.8.24"
testcases = { path = "../testcases" }

[[bin]]
name = "forge"
path = "src/main.rs"
