[package]
name = "gas-algebra-ext"
version = "0.0.1"
authors = ["Pont Labs <opensource@pontlabs.com>"]
repository = "https://github.com/pont-core/aptos-labs"
homepage = "https://pontlabs.com"
license = "Apache-2.0"
publish = false
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
move-core-types = { workspace = true }
