[package]
name = "forge"
version = "0.0.0"
authors = ["Pont Labs <opensource@pontlabs.com>"]
description = "Pont end to end test framework"
repository = "https://github.com/aptos-labs/pont-core"
homepage = "https://pontlabs.com"
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
again = "0.1.2"
anyhow = { version = "1.0.57", features = ["backtrace"] }
async-trait = "0.1.53"
chrono = "0.4.19"
either = "1.6.1"
futures = "0.3.21"
hex = "0.4.3"
hyper = { version = "0.14.18", features = ["full"] }
hyper-tls = "0.5.0"
itertools = "0.10.0"
k8s-openapi = { version = "0.11.0", default-features = false, features = ["v1_15"] }
kube = { version = "0.51.0", features = ["jsonpatch"] }
num_cpus = "1.13.1"
once_cell = "1.10.0"
prometheus-http-query = "0.5.2"
rand = "0.7.3"
rayon = "1.5.2"
regex = "1.5.5"
reqwest = { version = "0.11.10", features = ["blocking", "json"] }
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"
serde_yaml = "0.8.24"
structopt = "0.3.21"
tempfile = "3.3.0"
termcolor = "1.1.2"
thiserror = "1.0.31"
tokio = { version = "1.21.0", features = ["full"] }
url = "2.2.2"

pont = { path = "../../crates/pont" }
pont-config = { path = "../../config" }
pont-genesis = { path = "../../crates/pont-genesis" }
pont-global-constants = { path = "../../config/global-constants" }
pont-infallible = { path = "../../crates/pont-infallible" }
pont-logger = { path = "../../crates/pont-logger" }
pont-rest-client = { path = "../../crates/pont-rest-client" }
pont-retrier = { path = "../../crates/pont-retrier" }
pont-sdk = { path = "../../sdk" }
pont-secure-storage = { path = "../../secure/storage" }
pontdb = { path = "../../storage/pontdb" }
cached-packages = { path = "../../pont-move/framework/cached-packages" }
framework = { path = "../../pont-move/framework" }
inspection-service = { path = "../../crates/inspection-service" }
json-patch = "0.2.6"
state-sync-driver = { path = "../../state-sync/state-sync-v2/state-sync-driver" }
transaction-emitter-lib = { path = "../../crates/transaction-emitter-lib" }

[features]
default = []
testing = ["pont-global-constants/testing"]
