[package]
name = "executor"
version = "0.1.0"
authors = ["Pont Labs <opensource@pontlabs.com>"]
description = "Pont executor"
repository = "https://github.com/aptos-labs/pont-core"
homepage = "https://pontlabs.com"
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
anyhow = "1.0.57"
bcs = { git = "https://github.com/aptos-labs/bcs", rev = "2cde3e8446c460cb17b0c1d6bac7e27e964ac169" }
fail = "0.5.0"
itertools = { version = "0.10.0", default-features = false }
once_cell = "1.10.0"
rayon = "1.5.2"
serde = { version = "1.0.137", features = ["derive"] }

pont-crypto = { path = "../../crates/pont-crypto" }
pont-gas = { path = "../../pont-move/pont-gas" }
pont-infallible = { path = "../../crates/pont-infallible" }
pont-logger = { path = "../../crates/pont-logger" }
pont-metrics-core = { path = "../../crates/pont-metrics-core" }
pont-secure-net = { path = "../../secure/net" }
pont-state-view = { path = "../../storage/state-view" }
pont-types = { path = "../../types" }
pont-vm = { path = "../../pont-move/pont-vm" }

consensus-types = { path = "../../consensus/consensus-types" }
executor-types = { path = "../executor-types" }
scratchpad = { path = "../../storage/scratchpad" }
storage-interface = { path = "../../storage/storage-interface" }

move-core-types = { git = "https://github.com/move-language/move", rev = "6a32284d6e04ea5bfa5919df9aac2ccb3ffa010e", features = ["address32"] }

[dev-dependencies]
proptest = "1.0.0"
rand = "0.7.3"

pont-config = { path = "../../config" }
pont-genesis = { path = "../../crates/pont-genesis", features = ["testing"] }
pont-temppath = { path = "../../crates/pont-temppath" }
pont-types = { path = "../../types", features = ["fuzzing"] }
pontdb = { path = "../../storage/pontdb" }
cached-packages = { path = "../../pont-move/framework/cached-packages" }
executor-test-helpers = { path = "../executor-test-helpers" }
storage-interface = { path = "../../storage/storage-interface", features = ["fuzzing"] }
vm-genesis = { path = "../../pont-move/vm-genesis" }

[features]
default = []
fuzzing = ["consensus-types/fuzzing", "pont-crypto/fuzzing", "pont-types/fuzzing", "storage-interface/fuzzing"]
failpoints = ["fail/failpoints", "pont-vm/failpoints"]
