[package]
name = "pont-sdk-builder"
version = "0.1.0"
authors = ["Pont Labs <opensource@pontlabs.com>"]
description = "Pont transaction-builder"
repository = "https://github.com/aptos-labs/pont-core"
homepage = "https://pontlabs.com"
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
anyhow = "1.0.57"
bcs = { git = "https://github.com/aptos-labs/bcs", rev = "2cde3e8446c460cb17b0c1d6bac7e27e964ac169" }
heck = "0.3.2"
once_cell = "1.10.0"
regex = "1.5.5"
serde-generate = { git = "https://github.com/aptos-labs/serde-reflection", rev = "839aed62a20ddccf043c08961cfe74875741ccba" }
serde-reflection = { git = "https://github.com/aptos-labs/serde-reflection", rev = "839aed62a20ddccf043c08961cfe74875741ccba" }
serde_yaml = "0.8.24"
structopt = "0.3.21"
textwrap = "0.15.0"

pont-types = { path = "../../types" }

move-core-types = { workspace = true }

[dev-dependencies]
cached-packages = { path = "../../pont-move/framework/cached-packages" }
framework = { path = "../framework" }
tempfile = "3.3.0"
which = "4.2.5"

[features]
default = []
