[package]
name = "transaction-emitter-lib"
version = "0.0.0"
authors = ["Pont Labs <opensource@pontlabs.com>"]
description = "Library for Pont transaction emitter"
repository = "https://github.com/aptos-labs/pont-core"
homepage = "https://pontlabs.com"
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
again = "0.1.2"
anyhow = { version = "1.0.57", features = ["backtrace"] }
async-trait = "0.1.53"
clap = "3.1.17"
futures = "0.3.21"
itertools = "0.10.3"
once_cell = "1.10.0"
rand = "0.7.3"
rand_core = "0.5.1"
reqwest = { version = "0.11.10", features = ["blocking", "json"] }
serde = { version = "1.0.137", features = ["derive"] }
tokio = { version = "1.21.0", features = ["full"] }
url = { version = "2.2.2", features = ["serde"] }

pont = { path = "../pont" }
pont-config = { path = "../../config" }
pont-crypto = { path = "../pont-crypto" }
pont-global-constants = { path = "../../config/global-constants" }
pont-infallible = { path = "../../crates/pont-infallible" }
pont-logger = { path = "../../crates/pont-logger" }
pont-rest-client = { path = "../pont-rest-client" }
pont-sdk = { path = "../../sdk" }
