[package]
name = "pont-jellyfish-merkle"
version = "0.1.0"
authors = ["Pont Labs <opensource@pontlabs.com>"]
description = "Pont jellyfish merkle"
repository = "https://github.com/aptos-labs/pont-core"
homepage = "https://pontlabs.com"
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
anyhow = "1.0.57"
bcs = { git = "https://github.com/aptos-labs/bcs", rev = "2cde3e8446c460cb17b0c1d6bac7e27e964ac169" }
byteorder = "1.4.3"
itertools = { version = "0.10.0", default-features = false }
num-derive = "0.3.3"
num-traits = "0.2.15"
once_cell = "1.10.0"
proptest = { version = "1.0.0", optional = true }
proptest-derive = { version = "0.3.0", optional = true }
rayon = "1.5.2"
serde = { version = "1.0.137", features = ["derive"] }
thiserror = "1.0.31"

pont-crypto = { path = "../../crates/pont-crypto" }
pont-crypto-derive = { path = "../../crates/pont-crypto-derive" }
pont-infallible = { path = "../../crates/pont-infallible" }
pont-logger = { path = "../../crates/pont-logger" }
pont-metrics-core = { path = "../../crates/pont-metrics-core" }
pont-types = { path = "../../types" }
storage-interface = { path = "../storage-interface" }

[dev-dependencies]
proptest = "1.0.0"
proptest-derive = "0.3.0"
rand = "0.7.3"

pont-crypto = { path = "../../crates/pont-crypto", features = ["fuzzing"] }
pont-types = { path = "../../types", features = ["fuzzing"] }
pontdb = { path = "../pontdb", features = ["fuzzing"] }

[features]
default = []
fuzzing = ["proptest", "proptest-derive", "pont-crypto/fuzzing", "pont-types/fuzzing"]
