[package]
name = "pont"
version = "0.4.0"
authors = ["Pont Labs <opensource@pontlabs.com>"]
description = "Pont tool for management of nodes and interacting with the blockchain"
repository = "https://github.com/aptos-labs/pont-core"
homepage = "https://pontlabs.com"
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
anyhow = "1.0.57"
async-trait = "0.1.53"
base64 = "0.13.0"
bcs = { git = "https://github.com/aptos-labs/bcs", rev = "2cde3e8446c460cb17b0c1d6bac7e27e964ac169" }
chrono = "0.4.19"
clap = "3.2.11"
clap_complete = "3.2.3"
dirs = "4.0.0"
futures = "0.3.21"
hex = "0.4.3"
itertools = "0.10.3"
rand = "0.7.3"
regex = "1.1.5"
reqwest = { version = "0.11.10", features = ["blocking", "json"] }
serde = "1.0.137"
serde_json = "1.0.81"
serde_yaml = "0.8.24"
shadow-rs = "0.16.2"
tempfile = "3.3.0"
termcolor = "1.1.3"
thiserror = "1.0.31"
tokio = { version = "1.21.0", features = ["full"] }
tokio-util = { version = "0.7.2", features = ["compat"] }
toml = "0.5.9"
walkdir = "2.3.2"

pont-bitvec = { path = "../../crates/pont-bitvec" }
pont-build-info = { path = "../../crates/pont-build-info" }
pont-config = { path = "../../config" }
pont-crypto = { path = "../pont-crypto", features = [] }
pont-faucet = { path = "../pont-faucet" }
pont-gas = { path = "../../pont-move/pont-gas" }
pont-genesis = { path = "../pont-genesis" }
pont-github-client = { path = "../../secure/storage/github" }
pont-global-constants = { path = "../../config/global-constants" }
pont-keygen = { path = "../pont-keygen" }
pont-logger = { path = "../pont-logger" }
pont-module-verifier = { path = "../../pont-move/pont-module-verifier" }
pont-node = { path = "../../pont-node" }
pont-rest-client = { path = "../../crates/pont-rest-client" }
pont-sdk = { path = "../../sdk" }
pont-telemetry = { path = "../pont-telemetry" }
pont-temppath = { path = "../pont-temppath" }
pont-transactional-test-harness = { path = "../../pont-move/pont-transactional-test-harness" }
pont-types = { path = "../../types" }
pont-vm = { path = "../../pont-move/pont-vm", features = ["testing"] }
vm-genesis = { path = "../../pont-move/vm-genesis" }

backup-cli = { path = "../../storage/backup/backup-cli" }
cached-packages = { path = '../../pont-move/framework/cached-packages' }
framework = { path = '../../pont-move/framework' }
move-deps = { path = "../../pont-move/move-deps", features = [
  "address32",
  "testing",
  "table-extension",
] }
storage-interface = { path = "../../storage/storage-interface" }

[features]
default = []
fuzzing = []
no-upload-proposal = []
indexer = ["pont-node/indexer"]
cli-framework-test-move = []

[build-dependencies]
shadow-rs = "0.16.2"
