[package]
name = "Examples"
version = "0.0.0"

[dependencies]
AptosFramework = { local = "../../framework/pont-framework" }
AptosToken = { local = "../../framework/aptos-token" }

[addresses]
aptos_framework = "0x1"
