{{- range $i, $e := until (int .Values.numFullnodeGroups) }}
{{- range $.Values.fullnode.groups }}
---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "pont-validator.fullname" $ }}-{{$i}}-{{ .name }}
  labels:
    {{- include "pont-validator.labels" $ | nindent 4 }}
spec:
  selector:
    {{- include "pont-validator.selectorLabels" $ | nindent 4 }}
    app.kubernetes.io/name: fullnode
    app.kubernetes.io/instance: fullnode-{{$i}}
    group: {{ .name }}
  type: {{ $.Values.service.fullnode.internal.type }}
  ports:
  - name: pontnet
    port: 6182
  - name: metrics
    port: 9101
  - name: api
    port: 8080

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "pont-validator.fullname" $ }}-{{$i}}-{{ .name }}-e{{ $.Values.chain.era }}
  labels:
    {{- include "pont-validator.labels" $ | nindent 4 }}
    app.kubernetes.io/name: fullnode
    app.kubernetes.io/instance: fullnode-{{$i}}
    group: {{ .name }}
spec:
  serviceName: {{ include "pont-validator.fullname" $ }}-{{$i}}-{{ .name }}
  replicas: {{ .replicas }}
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      {{- include "pont-validator.selectorLabels" $ | nindent 6 }}
      app.kubernetes.io/name: fullnode
      app.kubernetes.io/instance: fullnode-{{$i}}
      group: {{ .name }}
  volumeClaimTemplates:
  - metadata:
      name: fn
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: {{ $.Values.fullnode.storage.class }}
      resources:
        requests:
          storage: {{ $.Values.fullnode.storage.size }}
  template:
    metadata:
      labels:
        {{- include "pont-validator.selectorLabels" $ | nindent 8 }}
        app.kubernetes.io/name: fullnode
        app.kubernetes.io/instance: fullnode-{{$i}}
        group: {{ .name }}
      annotations:
        seccomp.security.alpha.kubernetes.io/pod: runtime/default
        checksum/fullnode.yaml: {{ tpl ($.Files.Get "files/configs/fullnode.yaml") $ | sha256sum }}
        prometheus.io/scrape: "true"
        prometheus.io/port: "9101"
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: fullnode
        image: {{ $.Values.validator.image.repo }}:{{ $.Values.validator.image.tag | default $.Values.imageTag }}
        imagePullPolicy: {{ $.Values.validator.image.pullPolicy }}
        command: ["/usr/local/bin/pont-node", "-f", "/opt/pont/etc/fullnode.yaml"]
      {{- with $.Values.fullnode }}
        resources:
          {{- toYaml .resources | nindent 10 }}
        env:
        - name: RUST_LOG
          value: {{ .rust_log }}
        - name: RUST_LOG_REMOTE
          value: {{ .rust_log_remote }}
        {{- if $.Values.validator.remoteLogAddress }}
        - name: STRUCT_LOG_TCP_ADDR
          value: {{ $.Values.validator.remoteLogAddress }}
        {{- end }}
        {{- if .force_enable_telemetry }}
        - name: APTOS_FORCE_ENABLE_TELEMETRY
          value: "true"
        {{- end }}
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: RUST_BACKTRACE
          value: "0"
      {{- end }}
        volumeMounts:
        - name: pont-config
          mountPath: /opt/pont/etc
        - name: genesis-config
          mountPath: /opt/pont/genesis
        - name: fn
          mountPath: /opt/pont/data
        ports:
        - containerPort: 6181
        - containerPort: 6182
        - containerPort: 8080
          name: api
        - containerPort: 9101
          name: metrics
        securityContext:
          {{- if $.Values.enablePrivilegedMode }}
          runAsUser: 0
          privileged: true
          {{- else }}
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          {{- end }}
      {{- with $.Values.fullnode }}
      {{- with .nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- if $.Values.enablePrivilegedMode }}
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
        {{- else }}
        runAsNonRoot: true
        runAsUser: 6180
        runAsGroup: 6180
        fsGroup: 6180
        {{- end }}
      {{- end }}
      volumes:
      - name: pont-config
        configMap:
          name: {{ include "pont-validator.fullname" $ }}-{{$i}}
      - name: genesis-config
        secret:
          secretName: {{ include "pont-validator.fullname" $ }}-{{$i}}-genesis-e{{ $.Values.chain.era }}
      serviceAccountName: {{ include "pont-validator.fullname" $ }}-fullnode
      {{- if $.Values.imagePullSecret }}
      imagePullSecrets:
      - name: {{ $.Values.imagePullSecret }}
      {{- end }}

{{- end }}
{{- end }}
