[package]
name = "state-sync-driver"
version = "0.1.0"
authors = ["Pont Labs <opensource@pontlabs.com>"]
repository = "https://github.com/aptos-labs/pont-core"
description = "The driver for state sync"
homepage = "https://pontlabs.com"
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
anyhow = "1.0.52"
async-trait = "0.1.53"
bcs = { git = "https://github.com/aptos-labs/bcs", rev = "2cde3e8446c460cb17b0c1d6bac7e27e964ac169" }
futures = "0.3.21"
once_cell = "1.10.0"
serde = { version = "1.0.137", default-features = false }
thiserror = "1.0.31"
tokio = { version = "1.21.0", features = ["full"] }
tokio-stream = "0.1.8"

pont-config = { path = "../../../config" }
pont-crypto = { path = "../../../crates/pont-crypto" }
pont-data-client = { path = "../../pont-data-client" }
pont-infallible = { path = "../../../crates/pont-infallible" }
pont-logger = { path = "../../../crates/pont-logger" }
pont-metrics-core = { path = "../../../crates/pont-metrics-core" }
pont-types = { path = "../../../types" }

consensus-notifications = { path = "../../inter-component/consensus-notifications" }
data-streaming-service = { path = "../data-streaming-service" }
event-notifications = { path = "../../inter-component/event-notifications" }
executor-types = { path = "../../../execution/executor-types" }
mempool-notifications = { path = "../../inter-component/mempool-notifications" }
schemadb = { path = "../../../storage/schemadb" }
scratchpad = { path = "../../../storage/scratchpad" }
storage-interface = { path = "../../../storage/storage-interface" }

[dev-dependencies]
anyhow = "1.0.57"
async-trait = "0.1.53"
bcs = { git = "https://github.com/aptos-labs/bcs", rev = "2cde3e8446c460cb17b0c1d6bac7e27e964ac169" }
claims = "0.7"
mockall = "0.11.0"
rand = "0.7.3"

pont-crypto = { path = "../../../crates/pont-crypto" }
pont-genesis = { path = "../../../crates/pont-genesis", features = ["testing"] }
pont-temppath = { path = "../../../crates/pont-temppath" }
pont-time-service = { path = "../../../crates/pont-time-service", features = ["async", "testing"] }
pont-vm = { path = "../../../pont-move/pont-vm" }
pontdb = { path = "../../../storage/pontdb" }
channel = { path = "../../../crates/channel" }
executor = { path = "../../../execution/executor" }
executor-test-helpers = { path = "../../../execution/executor-test-helpers" }
move-core-types = { workspace = true }
network = { path = "../../../network", features = ["fuzzing"] }
storage-service-client = { path = "../../storage-service/client" }
storage-service-types = { path = "../../storage-service/types" }
vm-genesis = { path = "../../../pont-move/vm-genesis", features = ["fuzzing"] }
