[package]
name = "peer-monitoring-service-types"
version = "0.1.0"
authors = ["Pont Labs <opensource@pontlabs.com>"]
description = "Common types offered by the peer monitoring service"
repository = "https://github.com/aptos-labs/pont-core"
homepage = "https://pontlabs.com"
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
serde = { version = "1.0.124", default-features = false }
thiserror = "1.0.24"

pont-config = { path = "../../../config" }

network = { path = "../../../network" }
