[package]
name = "backup-service"
version = "0.1.0"
authors = ["Pont Labs <opensource@pontlabs.com>"]
repository = "https://github.com/aptos-labs/pont-core"
homepage = "https://pontlabs.com"
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
anyhow = "1.0.57"
bcs = { git = "https://github.com/aptos-labs/bcs", rev = "2cde3e8446c460cb17b0c1d6bac7e27e964ac169" }
bytes = "1.1.0"
hyper = "0.14.18"
once_cell = "1.10.0"
serde = { version = "1.0.137", default-features = false }
tokio = { version = "1.21.0", features = ["full"] }
warp = "0.3.2"

pont-crypto = { path = "../../../crates/pont-crypto" }
pont-logger = { path = "../../../crates/pont-logger" }
pont-metrics-core = { path = "../../../crates/pont-metrics-core" }
pont-types = { path = "../../../types" }

pontdb = { path = "../../pontdb" }
storage-interface = { path = "../../storage-interface" }

[dev-dependencies]
reqwest = { version = "0.11.10", features = ["blocking", "json"], default_features = false }

pont-config = { path = "../../../config" }
pont-temppath = { path = "../../../crates/pont-temppath" }
pontdb = { path = "../../pontdb", features = ["fuzzing"] }

[features]
fuzzing = ["pontdb/fuzzing"]
