[package]
name = "framework"
version = "0.1.0"
edition = "2021"
authors = ["Pont Labs <opensource@pontlabs.com>"]
description = "Pont stdlib"
repository = "https://github.com/aptos-labs/pont-core"
homepage = "https://pontlabs.com"
license = "Apache-2.0"
publish = false

[dependencies]
anyhow = "1.0.57"
pont-aggregator = { path = "../../pont-move/pont-aggregator" }
pont-crypto = { path = "../../crates/pont-crypto", features = ["fuzzing"] }
pont-module-verifier = { path = "../../pont-move/pont-module-verifier" }
pont-sdk-builder = { path = "../pont-sdk-builder" }
pont-state-view = { path = "../../storage/state-view" }
pont-types = { path = "../../types" }
base64 = "0.13.0"
bcs = { git = "https://github.com/aptos-labs/bcs", rev = "2cde3e8446c460cb17b0c1d6bac7e27e964ac169" }
better_any = "0.1.1"
clap = "3.1.8"
codespan-reporting = "0.11.1"
curve25519-dalek = { version = "3", default-features = false }
flate2 = "1.0.24"
gas-algebra-ext =  { path = "../gas-algebra-ext" }
include_dir = "0.7.2"
itertools = "0.10.0"
libsecp256k1 = "0.7.0"
log = "0.4.17"
move-binary-format = { workspace = true }
once_cell = "1.10.0"
proptest = { version = "1.0.0", optional = true }
proptest-derive = { version = "0.3.0", optional = true }
rayon = "1.5.2"
serde = { version = "1.0.137", default-features = false }
serde_bytes = "0.11.6"
serde_json = "1.0.81"
serde_yaml = "0.8.24"
sha2 = "0.9.3"
siphasher = "0.3.10"
smallvec = "1.8.0"
tempfile = "3.3.0"
tiny-keccak = { version = "2.0.2", features = ["keccak"] }

move-command-line-common = { workspace = true }
move-compiler ={ workspace = true }
move-core-types ={ workspace = true }
move-docgen ={ workspace = true }
move-model ={ workspace = true }
move-package ={ workspace = true }
move-prover ={ workspace = true }
move-prover-boogie-backend ={ workspace = true }
move-stackless-bytecode ={ workspace = true }
move-table-extension ={ workspace = true }
move-vm-runtime ={ workspace = true }
move-vm-types ={ workspace = true }
rand_core = "0.5.1"

[dev-dependencies]
pont-gas = { path = "../../pont-move/pont-gas" }
pont-vm = { path = "../../pont-move/pont-vm", features = ["testing"] }
claims = "0.7"

cached-packages = { path = "cached-packages" }  # keep to ensure build of artifacts
move-cli = { workspace = true }
move-prover = { workspace = true }

move-unit-test = { workspace = true }

[features]
default = []
fuzzing = ["pont-types/fuzzing", "proptest", "proptest-derive"]
testing = []

[lib]
doctest = false
