[package]
name = "pont-vm"
version = "0.1.0"
authors = ["Pont Labs <opensource@pontlabs.com>"]
description = "Pont VM runtime"
repository = "https://github.com/aptos-labs/pont-core"
homepage = "https://pontlabs.com"
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
anyhow = "1.0.57"
pont-crypto = { path = "../../crates/pont-crypto" }
pont-crypto-derive = { path = "../../crates/pont-crypto-derive" }
bcs = { git = "https://github.com/aptos-labs/bcs", rev = "2cde3e8446c460cb17b0c1d6bac7e27e964ac169" }
dashmap = "5.2.0"
fail = "0.5.0"
num_cpus = "1.13.1"
once_cell = "1.10.0"
rayon = "1.5.2"
serde = { version = "1.0.137", default-features = false }
serde_json = "1.0.81"
smallvec = "1.8.0"
tracing = "0.1.34"

pont-aggregator = { path = "../pont-aggregator" }
pont-gas = { path = "../pont-gas" }
pont-logger = { path = "../../crates/pont-logger" }
pont-metrics-core = { path = "../../crates/pont-metrics-core" }
pont-module-verifier = { path = "../../pont-move/pont-module-verifier" }
pont-parallel-executor = { path = "../parallel-executor" }
pont-state-view = { path = "../../storage/state-view" }
pont-types = { path = "../../types" }

framework =  { path = "../framework" }
move-binary-format = { workspace = true }
move-bytecode-utils = { workspace = true }
move-bytecode-verifier = { workspace = true }
move-core-types = { workspace = true }
move-stdlib = { workspace = true }
mvhashmap = { path = "../mvhashmap" }

move-table-extension = { workspace = true }
move-vm-runtime = { workspace = true }
move-vm-test-utils = { workspace = true }
move-vm-types = { workspace = true }
read-write-set-dynamic = { workspace = true }

move-unit-test = { workspace = true, optional = true }

[dev-dependencies]
proptest = "1.0.0"

pont-types = { path = "../../types", features = ["fuzzing"] }

[features]
default = []
mirai-contracts = []
fuzzing = ["move-core-types/fuzzing", "move-binary-format/fuzzing", "move-vm-types/fuzzing", "framework/fuzzing"]
failpoints = ["fail/failpoints", "move-vm-runtime/failpoints"]
testing = ["move-unit-test", "framework/testing"]
