[package]
name = "pont-parallel-executor"
version = "0.1.0"
authors = ["Pont Labs <opensource@pontlabs.com>"]
description = "Pont parallel transaction executor library"
repository = "https://github.com/aptos-labs/pont-core"
homepage = "https://pontlabs.com"
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
anyhow = "1.0.57"
arc-swap = "1.5.0"
bcs = { git = "https://github.com/aptos-labs/bcs", rev = "2cde3e8446c460cb17b0c1d6bac7e27e964ac169" }
criterion = { version = "0.3.5", optional = true }
crossbeam = "0.8.1"
crossbeam-queue = "0.3.5"
dashmap = "5.2.0"
num_cpus = "1.13.1"
once_cell = "1.10.0"
proptest = { version = "1.0.0", optional = true }
proptest-derive = { version = "0.3.0", optional = true }
rayon = "1.5.2"

pont-aggregator = { path = "../pont-aggregator" }
pont-infallible = { path = "../../crates/pont-infallible" }
pont-metrics-core = { path = "../../crates/pont-metrics-core" }
pont-state-view = { path = "../../storage/state-view" }
pont-types = { path = "../../types" }

mvhashmap = { path = "../mvhashmap" }

[dev-dependencies]
claims = "0.7"
criterion = "0.3.5"
proptest = "1.0.0"
proptest-derive = "0.3.0"
rand = "0.7.3"

[features]
fuzzing = ["criterion", "proptest", "proptest-derive"]

[[bench]]
name = "scheduler_benches"
harness = false
required-features = ["fuzzing"]
