[package]
name = "Examples"
version = "0.0.0"

[dependencies]
PontFramework = { local = "../../framework/pont-framework" }
PontToken = { local = "../../framework/pont-token" }

[addresses]
pont_framework = "0x1"
