[package]
name = "artifacts-test"
version = "0.1.0"
edition = "2021"
authors = ["Pont Labs <opensource@pontlabs.com>"]
repository = "https://github.com/aptos-labs/pont-core"
homepage = "https://pontlabs.com"
license = "Apache-2.0"
publish = false

[dependencies]
dir-diff = "0.3.2"
framework = { path = ".." }
fs_extra = "1.2.0"
tempfile = "3.3.0"

[lib]
doctest = false
