[package]
name = "pont-vault-client"
version = "0.1.0"
authors = ["Pont Labs <opensource@pontlabs.com>"]
repository = "https://github.com/aptos-labs/pont-core"
description = "Pont's Restful Vault Client"
homepage = "https://pontlabs.com"
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
base64 = "0.13.0"
chrono = "0.4.19"
native-tls = "0.2.10"
once_cell = "1.10.0"
proptest = { version = "1.0.0", optional = true }
serde = { version = "1.0.137", features = ["derive"], default-features = false }
serde_json = "1.0.81"
thiserror = "1.0.31"
ureq = { version = "1.5.4", features = ["json", "native-tls"], default-features = false }

pont-crypto = { path = "../../../crates/pont-crypto" }
pont-proptest-helpers = { path = "../../../crates/pont-proptest-helpers", optional = true }
pont-types = { path = "../../../types", optional = true }

[dev-dependencies]
proptest = "1.0.0"

pont-proptest-helpers = { path = "../../../crates/pont-proptest-helpers" }
pont-types = { path = "../../../types", features = ["fuzzing"] }

[features]
fuzzing = ["proptest", "pont-proptest-helpers", "pont-types", "pont-types/fuzzing"]
