[package]
name = "pont-proptest-helpers"
version = "0.1.0"
authors = ["Pont Labs <opensource@pontlabs.com>"]
description = "Pont proptest helpers"
repository = "https://github.com/aptos-labs/pont-core"
homepage = "https://pontlabs.com"
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
crossbeam = "0.8.1"
proptest = "1.0.0"
proptest-derive = "0.3.0"


