name: add artifact links to pull request
on:
  workflow_run:
    workflows: [Build Pont]
    types: [completed]

jobs:
  artifacts-url-comments:
    name: add artifact links to pull request
    runs-on: ubuntu-20.04
    steps:
      - name: add artifact links to pull request
        uses: tonyhallett/artifacts-url-comments@v1.1.0
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            prefix: Here are the artifacts 
            format: name
            addTo: pull