[package]
name = "pont-data-client"
version = "0.1.0"
authors = ["Pont Labs <opensource@pontlabs.com>"]
description = "The Pont data client"
repository = "https://github.com/aptos-labs/pont-core"
homepage = "https://pontlabs.com"
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
async-trait = "0.1.53"
futures = "0.3.21"
itertools = "0.10.0"
rand = "0.7.3"
serde = { version = "1.0.137", default-features = false }
thiserror = "1.0.31"
tokio = { version = "1.21.0", features = ["full"] }

pont-config = { path = "../../config" }
pont-crypto = { path = "../../crates/pont-crypto" }
pont-id-generator = { path = "../../crates/pont-id-generator" }
pont-infallible = { path = "../../crates/pont-infallible" }
pont-logger = { path = "../../crates/pont-logger" }
pont-metrics-core = { path = "../../crates/pont-metrics-core" }
pont-time-service = { path = "../../crates/pont-time-service", features = ["async"] }
pont-types = { path = "../../types" }

netcore = { path = "../../network/netcore" }
network = { path = "../../network" }
storage-service-client = { path = "../storage-service/client" }
storage-service-types = { path = "../storage-service/types" }

[dev-dependencies]
bcs = { git = "https://github.com/aptos-labs/bcs", rev = "2cde3e8446c460cb17b0c1d6bac7e27e964ac169" }
claims = "0.7"
maplit = "1.0.2"
tokio = { version = "1.21.0", features = ["rt", "macros"], default-features = false }

pont-time-service = { path = "../../crates/pont-time-service", features = ["async", "testing"] }
channel = { path = "../../crates/channel" }
network = { path = "../../network", features = ["fuzzing"] }
storage-service-server = { path = "../storage-service/server" }
