[package]
name = "pont-fh-stream"
version = "0.1.0"
authors = ["Pont Labs <opensource@pontlabs.com>"]
description = "Pont StreamingFast Firehose Stream"
repository = "https://github.com/aptos-labs/pont-core"
homepage = "https://pontlabs.com"
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
anyhow = "1.0.57"
base64 = "0.13.0"
bytes = "1.1.0"
chrono = { version = "0.4.19", default-features = false, features = ["clock", "serde"] }
fail = "0.5.0"
futures = "0.3.21"
hex = "0.4.3"
hyper = "0.14.18"
once_cell = "1.10.0"
prost = "0.10.4"
serde = { version = "1.0.137", features = ["derive"], default-features = false }
serde_json = { version = "1.0.81", features = ["preserve_order"] }
tokio = { version = "1.21.0", features = ["full"] }

pont-api = { path = "../../../api", package = "pont-api" }
pont-api-types = { path = "../../../api/types" }
pont-bitvec = { path = "../../../crates/pont-bitvec" }
pont-config = { path = "../../../config" }
pont-logger = { path = "../../../crates/pont-logger" }
pont-mempool = { path = "../../../mempool" }
pont-metrics-core = { path = "../../../crates/pont-metrics-core" }
pont-protos = { path = "../../../crates/pont-protos" }
pont-types = { path = "../../../types" }
pont-vm = { path = "../../../pont-move/pont-vm" }
storage-interface = { path = "../../../storage/storage-interface" }

move-binary-format = { workspace = true }
move-core-types = { workspace = true }
move-package = { workspace = true }

[dev-dependencies]
goldenfile = "1.1.0"
rand = "0.7.3"
regex = "1.5.5"

pont-api-test-context  = { path = "../../../api/test-context" }
pont-crypto = { path = "../../../crates/pont-crypto" }
pont-genesis = { path = "../../../crates/pont-genesis", features = ["testing"] }
pont-global-constants = { path = "../../../config/global-constants" }
pont-mempool = { path = "../../../mempool", features = ["fuzzing"] }
pont-proptest-helpers = { path = "../../../crates/pont-proptest-helpers" }
pont-sdk = { path = "../../../sdk" }
pont-secure-storage = { path = "../../../secure/storage" }
pont-temppath = { path = "../../../crates/pont-temppath" }
pont-vm = { path = "../../../pont-move/pont-vm" }
pontdb = { path = "../../../storage/pontdb", features = ["fuzzing"] }
executor = { path = "../../../execution/executor" }
executor-types = { path = "../../../execution/executor-types" }
framework = { path = "../../../pont-move/framework" }
mempool-notifications = { path = "../../../state-sync/inter-component/mempool-notifications" }
vm-validator = { path = "../../../vm-validator" }

[features]
failpoints = ["fail/failpoints"]
